using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GalacticARM.Decoding
{
    public enum InstructionInfo
    {
        W,
        X,
        NULL,
        S,
        D,
        Q,
        B,
        H,
        _32_bit_to_single_precision,
        Single_precision_to_32_bit,
        _32_bit_to_double_precision,
        Double_precision_to_32_bit,
        _64_bit_to_single_precision,
        Single_precision_to_64_bit,
        _64_bit_to_double_precision,
        Double_precision_to_64_bit,
        Single_precision,
        Double_precision,
        Single_precision_zero,
        Double_precision_zero,
        Single_precision_to_double_precision,
        Single_precision_to_half_precision,
        Double_precision_to_single_precision,
        Double_precision_to_half_precision,
        Half_precision_to_single_precision,
        Half_precision_to_double_precision,
        Top_half_of_128_bit_to_64_bit,
        _64_bit_to_top_half_of_128_bit,
        Scalar,
        Vector,
        _32_bit,
        _64_bit,
        _32_bit_shifted_immediate,
        _16_bit_shifted_immediate,
        _16_bit,
        _32_bit_shifting_ones,
        _8_bit,
        _64_bit_scalar,
        _64_bit_vector,
        Single_register_table,
        Two_register_table,
        Three_register_table,
        Four_register_table,
        No_offset,
        Four_registers,
        Three_registers,
        One_register,
        Two_registers,
        Register_offset,
        Four_registers_register_offset,
        Three_registers_register_offset,
        One_register_register_offset,
        Two_registers_register_offset,
        Immediate_offset,
        Four_registers_immediate_offset,
        Three_registers_immediate_offset,
        One_register_immediate_offset,
        Two_registers_immediate_offset,
        _8_bit_register_offset,
        _16_bit_register_offset,
        _32_bit_register_offset,
        _64_bit_register_offset,
        _8_bit_immediate_offset,
        _16_bit_immediate_offset,
        _32_bit_immediate_offset,
        _64_bit_immediate_offset,
    }
}
